version: "1"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FenceLive
      POSTGRES_USER: postgres
    volumes:
      - ./ci/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - FenceLive

networks:
  FenceLive: