name: Go

on:
  pull_request:
    branches: [master]

jobs:


  Testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.7-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: FenceLive
          POSTGRES_USER: postgres
    

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        
      - name: apply migrations
        run: |
        cd migrations
        go run github.com/pressly/goose/v3/cmd/goose postgres 'postgres://postgres:postgres@localhost:5432/FenceLive?sslmode=disable' up

      - name: jet generate
        run: go run github.com/go-jet/jet/v2/cmd/jet -dsn=postgres://postgres:postgres@localhost:5432/FenceLive?sslmode=disable -path=./internal/ports/database/gen

      - name: run tests
        run: go test -v ./...
           