name: Publish Docker image

on: 
  release:
    types: [published]

jobs:
  push_to_registry:
    services:
      postgres:
        image: postgres:13.7-alpine
        ports:
          - "5434:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fencelive
          POSTGRES_USER: postgres

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        
      - name: apply migrations
        run: |
          cd fencelive
          go mod tidy
          cd migrations
          go run github.com/pressly/goose/v3/cmd/goose postgres 'postgres://postgres:postgres@localhost:5434/fencelive?sslmode=disable' up

      - name: jet generate 
        run: |
          cd fencelive
          go mod tidy
          go generate ./cmd/main.go


      - name: Build fencelive
        run: |
          cd fencelive
          bash ./ci/build.sh
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: espeletia/fencelive_be
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./fencelive/ci/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}