name: unit_tests

on: pull_request

jobs:


  Testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.7-alpine
        ports:
          - "5434:5432"
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fencelive
          POSTGRES_USER: postgres
    

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
        
      - name: apply migrations
        run: |
          cd fencelive
          cd migrations
          go run github.com/pressly/goose/v3/cmd/goose postgres 'postgres://postgres:postgres@localhost:5434/fencelive?sslmode=disable' up

      - name: jet generate
        run: |
          cd fencelive
          go run github.com/go-jet/jet/v2/cmd/jet -dsn=postgres://postgres:postgres@localhost:5434/fencelive?sslmode=disable -path=./internal/ports/database/gen

      - name: run tests
        run: |
          cd fencelive
          go test -v ./...
           